### ISSUE TITLE
util/hash.h > error: ‘id_’ was not declared in this scope

### ISSUE THREAD

**Issue by PearCoding** [AnyDSL/thorin#111]
The following line will not compile if THORIN_ENABLE_CHECKS is not defined. Maybe just return 0 instead?

https://github.com/AnyDSL/thorin/blob/2b8e503436b049b592cf4ba9d651fea4f99c15c8/src/thorin/util/hash.h#L185

Interestingly, the issue just appeared out of nowhere... never got that error before.

**Comment by PearCoding** [comment]
More information about my system:

Branch:         master
Config:          default config.sh with ninja
compiler:       gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
distro:            Ubuntu 21.04

I suppose an update from gcc made the bug appear.

**Comment by madmann91** [comment]
Should be fixed now
