### ISSUE TITLE
Memory monads

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/thorin#12]
I got a function with only memory monads as arguments (3 of them). Hence the assertion

    thorin/be/llvm/llvm.cpp:253 assert(n == num_args || n+1 == num_args);

has been triggered in the code generation phase (in my case n = 0 and num_args = 3). How is that even possible ? Shouldn't there be only one memory monad argument ?

I am not able to reproduce the bug with a simple example. Maybe this is linked to partial evaluation. I can post the whole raytracer code that generates this bug, if you are interested.

**Comment by leissa** [comment]
that's really weird, indeed. There should only be one mem value live at a time. Can you point me to the revision and build command?

**Comment by madmann91** [comment]
You mean the revision of the raytracer ? If so, I will have to create a branch for that (called monad_bug I guess). If not then I suppose you are referring to the impala/thorin version : I am using the master branch with the latest commits.

**Comment by leissa** [comment]
yep, create a branch for the ray tracer

**Comment by madmann91** [comment]
Done. The build command is simply make, once you have set up the cmake variables correctly.

**Comment by leissa** [comment]
ic

**Comment by madmann91** [comment]
I forgot to mention that the problem is located within :

      src/impala/scene/material.impala

The function that seems to be causing the problem is :

      fn compute_differentials(...) -> (Vec2, Vec2)

If I change the return value from __(Vec2, Vec2)__  to __float__ and return an undefined float, then the program compiles fine. Maybe this problem is related to tuples ?

**Comment by leissa** [comment]
really stupid bug... fixed now
