### ISSUE TITLE
Array equality

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/thorin#13]
Array equality is authorized in Impala, but not supported by Thorin. The following code breaks :

    extern "C" {
        fn puts(&[u8]) -> ();
    }

    fn main() -> () {
        let a = [1, 2];
        let b = [3, 4];
        if a == b {
            puts("arrays are equal");    
        }
    }

It generates the following assertion :

    impala: /space/perard/sources/thorin/src/thorin/util/cast.h:29: L* thorin::scast(R*) [with L = thorin::VectorTypeNode; R = thorin::MagicCast<thorin::TypeNode>]: Assertion `(!r || dynamic_cast<L*>(r)) && "cast not possible"' failed.

Should I implement it ? Or should it be forbidden in the front-end ?

**Comment by leissa** [comment]
Should be forbidden in the front-end. Can you have a look into the semantic analysis?

**Comment by madmann91** [comment]
Ok. I'll do that then. But the possibility of comparing two definite size arrays was practical, I must say.

**Comment by leissa** [comment]
once we have operator overloading we can re-implement that feature in the library.
