### ISSUE TITLE
Very simple code crashes during PE (new_master)

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/thorin#24]
The following code emits the `world().lambdas().find(lambda) != world().lambdas().end()` assertion on __new_master__ (run with -emit-llvm) :

    fn max(a: f32, b: f32) -> f32 @{
        if a > b { a } else { b }
    }

    extern fn traverse_accel() -> () @{
        let t0_y : f32;
        let t0 = max(t0_y, t0_y);
    }

Inlining the function `max`, removing the _@_ sign on the first line, or specifying a concrete value for `t0_y` removes the assertion.

**Comment by richardmembarth** [comment]
fixed in new_master
