### ISSUE TITLE
'May be undefined' message

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/thorin#27]
I got the 'May be undefined' message after compiling the following piece of code:

    fn iterate_children(mut node_id: &i32) -> () {
        for call_me() {
            if 42 < *node_id {
                // Nothing to see here
            }
        }
        *node_id = 42;
    }

    fn call_me(body: fn() -> ()) -> () {
        body();
    }

    extern fn traverse_accel() -> () {
        let mut node_id = 42;
        while node_id < 42 {
            @iterate_children(&node_id);
        }
    }

**Comment by leissa** [comment]
I will close this issue when I've written a test case which works with our test suite.

**Comment by leissa** [comment]
just discovered, that the original case still triggers this message... I could have sworn I tested it...
