### ISSUE TITLE
Thorin segfault on unreachable code when emitting LLVM

### ISSUE THREAD

**Issue by richardmembarth** [AnyDSL/thorin#29]
The following code segfaults when generating LLVM code due to unreachable code (llvm.cpp:321):

```
extern "C" {
  fn sqrtf(f32) -> f32;
}
extern
fn thorin_test() -> () {
    let check: [float * 1]; 
    let X = ~[12:float];
    let sval = sqrtf(X(0));
    if check(0) > 0f { }   
}
```

**Comment by madmann91** [comment]
The variable `check` needs an initializer. If you provide one, this now works on master. I tested the program with these initializers:

- `undef[[float * 1]]()`
- `[1.0f]`
- `[-1.0f]`

I am therefore closing this issue.
