### ISSUE TITLE
reserve_shared triggers assertion failure

### ISSUE THREAD

**Issue by KareemErgawy** [AnyDSL/thorin#46]
This code fragment:

```rust
extern "thorin" {
    fn cuda(i32, (i32, i32, i32), (i32, i32, i32), fn() -> ()) -> (); 
    fn reserve_shared[T](i32) -> &[3][T];
}
fn launch(size: i32) -> () {
    with cuda(0, (size, 1, 1), (size, 1, 1)) {
        let shrd = reserve_shared[f32](size);
    }   
}

fn main() -> i32 {
    @launch(128);
    @launch(256);
    0   
}
```

results in an assertion failure:

> Expression: (!r || dynamic_cast<L*>(r)) && "cast not possible"

at:

> File: W:/thesis/anydsl/thorin/src/thorin/util/cast.h, Line 29

The **reserve_shared** call triggers the problem. Also the problem is only triggered when more than  **launch** calls are present.

**Comment by leissa** [comment]
Thanks for reporting. Can you give me a self-contained version I can easily debug?

**Comment by KareemErgawy** [comment]
Sorry for the long example. I updated the issue with a shorter version.

**Comment by leissa** [comment]
thanks. But I was more asking for *self-contained* version. A file which works out-of-the-box - where all built-in functions are already declared and so forth.

**Comment by KareemErgawy** [comment]
Oh my bad again. Updated the code.

**Comment by richardmembarth** [comment]
I've updated the code to include declarations of ```cuda``` and ```reserve_shared``` intrinsics.
The code SegFaults on the master branch, but works on the alternate_evalops branch.

**Comment by leissa** [comment]
Thanks both of you. So, we are about to merge ```alternate_evalop``` into ```master```. Should I open a pull request so we can discuss any remaining issues and by doing this close this bug, too?

**Comment by richardmembarth** [comment]
Sounds like a plan!

**Comment by leissa** [comment]
just looked into it. The bug should in principal also affect ```alternate_evalop```. It's a bit hard to write a test case for that. So I'm closing this now.
