### ISSUE TITLE
Invalid casts can result in assertion failure

### ISSUE THREAD

**Issue by RalfJung** [AnyDSL/thorin#5]
Invalid casts can result in an assertion failure in thorin. That's highlight frustrating, as it quickly happens and it's fairly hard to figure out which part of the source triggers the problem.
See the last commit in <https://github.com/AnyDSL/imbatracer/commits/impala-cast> for an example.

**Comment by richardmembarth** [comment]
This has been resolved in the meantime:
```
imbatracer/src/main/instance.impala:20 col 34 - 48: error: invalid source and destination types for cast operator, got 'Instance' and '&u8'
```
