### ISSUE TITLE
amdgpu support

### ISSUE THREAD

**Issue by leissa** [AnyDSL/thorin#66]

**Comment by richardmembarth** [comment]
A working amdgpu backend will require LLVM 4.0.
This will most likely not land in [0.4](https://github.com/AnyDSL/thorin/milestone/1).

**Comment by richardmembarth** [comment]
This is now working and can be merged into the llvm_40 branch:
https://github.com/AnyDSL/thorin/tree/amdgpu

**Comment by richardmembarth** [comment]
Merged.
