### ISSUE TITLE
sizeof

### ISSUE THREAD

**Issue by RalfJung** [AnyDSL/thorin#7]
Es wäre echt praktisch, wenn wir einen sizeof-Operator bekommen könnten. Momentan berechnen wir die Größen diverser Structs (inklusive Padding) von Hand, das ist durchaus ziemlich fehleranfällig.

**Comment by leissa** [comment]
sizeof is now supported.

**Comment by richardmembarth** [comment]
Thorin segfaults as soon as code that contains sizeof is PEd or if sizeof is used after a code block that triggered PE.

**Comment by leissa** [comment]
I consider that a different issue but as I'm too lazy to open a new one, let's track it here :)
