### ISSUE TITLE
Assertion `i < num_params()' failed

### ISSUE THREAD

**Issue by KareemErgawy** [AnyDSL/thorin#78]
I get the following assertion failure when I build Stincilla:
```
impala: /home/ergawy/anydsl/thorin/src/thorin/continuation.h:122: const thorin::Param* thorin::Continuation::param(size_t) const: Assertion `i < num_params()' failed.
```
`num_params()` is 0. Not sure if this is a bug or a problem with my build!

**Comment by richardmembarth** [comment]
I don't see this assertion here.

You're most likely linking against an old version of thorin.
My guess is that you have both libthorin.a and libthorin.so lying around, one being outdated.

**Comment by KareemErgawy** [comment]
Thanks. Erroneous linking was the problem.
